[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="users" type="ru.itmo.tpl.model.User[]" --]
[#-- @ftlvariable name="user" type="ru.itmo.tpl.model.User" --]
[#-- @ftlvariable name="posts" type="ru.itmo.tpl.model.Post[]" --]
[#-- @ftlvariable name="menu" type="ru.itmo.tpl.model.MenuElement[]" --]
